version: '3'

services:
  insta_mysql:
    image: mysql:8.2.0
    container_name: insta_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: django_insta
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    restart: always

