# Generated by Django 5.0 on 2024-01-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_number', models.IntegerField()),
                ('like_user_email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'FeedLike',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_user', models.CharField(max_length=30)),
                ('following', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Follow',
            },
        ),
    ]
