# Generated by Django 5.0 on 2024-01-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('password', models.CharField(default=True, max_length=255)),
                ('realname', models.CharField(default=True, max_length=30)),
                ('nickname', models.CharField(default=True, max_length=30, unique=True)),
                ('profile_image', models.TextField(default=False)),
                ('email', models.EmailField(default=True, max_length=254, unique=True)),
                ('follow_number', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
