# Generated by Django 5.0 on 2023-12-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.TextField(default='backImage/profile/default_profile.jpg'),
        ),
    ]
